version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.1
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore "src/Hello CircleCI.csproj"
     - run:
         name: Build App
         command:
           dotnet build "src/Hello CircleCI.csproj"
     - run:
         name: Restore Test packages
         command:
           dotnet restore "test/Hello CircleCITest.csproj"    
     - run:
         name: Build Test App
         command:
           dotnet build "test/Hello CircleCITest.csproj"
     - run:
         name: Test App
         command:
           dotnet test "test/Hello CircleCITest.csproj"
